id: A28F2AEF2
title: Regularly Recitable Prayer to the Root Guru, Loter Wangpo
type: translation
pechas:
- I25BA860D
- I63BD67B9
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:38:33.872740
  last_modified_at: 2023-01-04 12:38:33.872751
  collections:
  - Jamyang Loter Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I25BA860D/5576: E609
  I63BD67B9/4CC2: E609
